package com.dephoegon.delbase.aid.event;

import com.dephoegon.delbase.aid.block.colorShift.axis.cutSandStone;
import com.dephoegon.delbase.aid.block.colorShift.fence.*;
import com.dephoegon.delbase.aid.block.colorShift.gen.chiseledSandStone;
import com.dephoegon.delbase.aid.block.colorShift.gen.normSandStone;
import com.dephoegon.delbase.aid.block.colorShift.gen.smoothSandStone;
import com.dephoegon.delbase.aid.block.colorShift.grav.sandBlock;
import com.dephoegon.delbase.aid.block.colorShift.grav.solidSandBlock;
import com.dephoegon.delbase.aid.block.colorShift.slab.*;
import com.dephoegon.delbase.aid.block.colorShift.stair.*;
import com.dephoegon.delbase.aid.block.colorShift.wall.*;
import com.dephoegon.delbase.aid.block.modExtensions.concreteSlab;
import com.dephoegon.delbase.aid.block.modExtensions.concreteStair;
import com.dephoegon.delbase.aid.block.modExtensions.concreteWall;
import net.minecraft.core.BlockPos;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

import static com.dephoegon.delbase.aid.util.blockArrayList.*;
import static com.dephoegon.delbase.aid.util.colorMixInteraction.ColorLogic;
import static com.dephoegon.delbase.block.axis.axiCutSandStones.*;
import static com.dephoegon.delbase.block.fence.fenceChiseledSandStone.*;
import static com.dephoegon.delbase.block.fence.fenceConcrete.*;
import static com.dephoegon.delbase.block.fence.fenceCutSandStone.*;
import static com.dephoegon.delbase.block.fence.fenceSand.*;
import static com.dephoegon.delbase.block.fence.fenceSandStone.*;
import static com.dephoegon.delbase.block.fence.fenceSmoothSandStone.*;
import static com.dephoegon.delbase.block.fence.fenceTerracotta.*;
import static com.dephoegon.delbase.block.general.genChiseledSandStones.*;
import static com.dephoegon.delbase.block.general.genSandStones.*;
import static com.dephoegon.delbase.block.general.genSmoothSandStones.*;
import static com.dephoegon.delbase.block.gravity.gravColorSands.*;
import static com.dephoegon.delbase.block.gravity.solidSandColors.*;
import static com.dephoegon.delbase.block.slab.slabChiseledSandStones.*;
import static com.dephoegon.delbase.block.slab.slabChiseledSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slab.slabConcrete.*;
import static com.dephoegon.delbase.block.slab.slabCutSandStones.*;
import static com.dephoegon.delbase.block.slab.slabCutSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slab.slabSandStones.*;
import static com.dephoegon.delbase.block.slab.slabSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slab.slabSands.*;
import static com.dephoegon.delbase.block.slab.slabSandsEnergy.*;
import static com.dephoegon.delbase.block.slab.slabSmoothSandStones.*;
import static com.dephoegon.delbase.block.slab.slabSmoothSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slab.slabTerracotta.*;
import static com.dephoegon.delbase.block.stair.stairChiseledSandStones.*;
import static com.dephoegon.delbase.block.stair.stairConcrete.*;
import static com.dephoegon.delbase.block.stair.stairCutSandStones.*;
import static com.dephoegon.delbase.block.stair.stairSandStones.*;
import static com.dephoegon.delbase.block.stair.stairSands.*;
import static com.dephoegon.delbase.block.stair.stairSmoothSandStones.*;
import static com.dephoegon.delbase.block.stair.stairTerracotta.*;
import static com.dephoegon.delbase.block.wall.wallChiseledSandStones.*;
import static com.dephoegon.delbase.block.wall.wallConcrete.*;
import static com.dephoegon.delbase.block.wall.wallCutSandStones.*;
import static com.dephoegon.delbase.block.wall.wallSandStone.*;
import static com.dephoegon.delbase.block.wall.wallSands.*;
import static com.dephoegon.delbase.block.wall.wallSmoothSandStones.*;
import static com.dephoegon.delbase.block.wall.wallTerracotta.*;
import static net.minecraft.world.level.block.Blocks.*;

public class typeSelector {
    public static InteractionResult axis_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 4;
        if (block instanceof cutSandStone || state == CUT_SANDSTONE.defaultBlockState() || state == CUT_RED_SANDSTONE.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, CUT_SANDSTONE.defaultBlockState(), CUT_RED_SANDSTONE.defaultBlockState(), BLOOD_CUT_SAND_STONE.get().defaultBlockState(), WHITE_CUT_SAND_STONE.get().defaultBlockState(), ORANGE_CUT_SAND_STONE.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE.get().defaultBlockState(), YELLOW_CUT_SAND_STONE.get().defaultBlockState(), LIME_CUT_SAND_STONE.get().defaultBlockState(), PINK_CUT_SAND_STONE.get().defaultBlockState(), GRAY_CUT_SAND_STONE.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE.get().defaultBlockState(), CYAN_CUT_SAND_STONE.get().defaultBlockState(), PURPLE_CUT_SAND_STONE.get().defaultBlockState(), BLUE_CUT_SAND_STONE.get().defaultBlockState(), GREEN_CUT_SAND_STONE.get().defaultBlockState(), BROWN_CUT_SAND_STONE.get().defaultBlockState(), BLACK_CUT_SAND_STONE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult slab_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 3;
        if (block instanceof chiseledSandStoneSlab) {
            return ColorLogic(world, blockPos, state, OVERRIDE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), OVERRIDE_RED_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof chiseledSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, OVERRIDE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), OVERRIDE_RED_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), blockIndex, inHand,playerEntity);
        }
        if (block instanceof cutSandStoneSlab || CUT_SANDSTONE_SLAB.defaultBlockState() == state || CUT_RED_SANDSTONE_SLAB.defaultBlockState() == state) {
            return ColorLogic(world, blockPos, state, CUT_SANDSTONE_SLAB.defaultBlockState(), CUT_RED_SANDSTONE_SLAB.defaultBlockState(), BLOOD_CUT_SAND_STONE_SLAB.get().defaultBlockState(), WHITE_CUT_SAND_STONE_SLAB.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_SLAB.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_SLAB.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_SLAB.get().defaultBlockState(), LIME_CUT_SAND_STONE_SLAB.get().defaultBlockState(), PINK_CUT_SAND_STONE_SLAB.get().defaultBlockState(), GRAY_CUT_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_SLAB.get().defaultBlockState(), CYAN_CUT_SAND_STONE_SLAB.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_SLAB.get().defaultBlockState(), BLUE_CUT_SAND_STONE_SLAB.get().defaultBlockState(), GREEN_CUT_SAND_STONE_SLAB.get().defaultBlockState(), BROWN_CUT_SAND_STONE_SLAB.get().defaultBlockState(), BLACK_CUT_SAND_STONE_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, OVERRIDE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), OVERRIDE_RED_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLOOD_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), WHITE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIME_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PINK_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GRAY_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), CYAN_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLUE_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GREEN_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BROWN_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLACK_CUT_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandSlab) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SAND_SLAB.get().defaultBlockState(), OVERRIDE_RED_SAND_SLAB.get().defaultBlockState(), BLOOD_SAND_SLAB.get().defaultBlockState(), WHITE_SAND_SLAB.get().defaultBlockState(), ORANGE_SAND_SLAB.get().defaultBlockState(), MAGENTA_SAND_SLAB.get().defaultBlockState(), LIGHT_BLUE_SAND_SLAB.get().defaultBlockState(), YELLOW_SAND_SLAB.get().defaultBlockState(), LIME_SAND_SLAB.get().defaultBlockState(), PINK_SAND_SLAB.get().defaultBlockState(), GRAY_SAND_SLAB.get().defaultBlockState(), LIGHT_GRAY_SAND_SLAB.get().defaultBlockState(), CYAN_SAND_SLAB.get().defaultBlockState(), PURPLE_SAND_SLAB.get().defaultBlockState(), BLUE_SAND_SLAB.get().defaultBlockState(), GREEN_SAND_SLAB.get().defaultBlockState(), BROWN_SAND_SLAB.get().defaultBlockState(), BLACK_SAND_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandSlabEnergy) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SAND_SLAB_ENERGY.get().defaultBlockState(), OVERRIDE_RED_SAND_SLAB_ENERGY.get().defaultBlockState(), BLOOD_SAND_SLAB_ENERGY.get().defaultBlockState(), WHITE_SAND_SLAB_ENERGY.get().defaultBlockState(), ORANGE_SAND_SLAB_ENERGY.get().defaultBlockState(), MAGENTA_SAND_SLAB_ENERGY.get().defaultBlockState(), LIGHT_BLUE_SAND_SLAB_ENERGY.get().defaultBlockState(), YELLOW_SAND_SLAB_ENERGY.get().defaultBlockState(), LIME_SAND_SLAB_ENERGY.get().defaultBlockState(), PINK_SAND_SLAB_ENERGY.get().defaultBlockState(), GRAY_SAND_SLAB_ENERGY.get().defaultBlockState(), LIGHT_GRAY_SAND_SLAB_ENERGY.get().defaultBlockState(), CYAN_SAND_SLAB_ENERGY.get().defaultBlockState(), PURPLE_SAND_SLAB_ENERGY.get().defaultBlockState(), BLUE_SAND_SLAB_ENERGY.get().defaultBlockState(), GREEN_SAND_SLAB_ENERGY.get().defaultBlockState(), BROWN_SAND_SLAB_ENERGY.get().defaultBlockState(), BLACK_SAND_SLAB_ENERGY.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneSlab || SANDSTONE_SLAB.defaultBlockState() == state || RED_SANDSTONE_SLAB.defaultBlockState() == state) {
            return ColorLogic(world, blockPos, state, SANDSTONE_SLAB.defaultBlockState(), RED_SANDSTONE_SLAB.defaultBlockState(), BLOOD_SAND_STONE_SLAB.get().defaultBlockState(), WHITE_SAND_STONE_SLAB.get().defaultBlockState(), ORANGE_SAND_STONE_SLAB.get().defaultBlockState(), MAGENTA_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_SLAB.get().defaultBlockState(), YELLOW_SAND_STONE_SLAB.get().defaultBlockState(), LIME_SAND_STONE_SLAB.get().defaultBlockState(), PINK_SAND_STONE_SLAB.get().defaultBlockState(), GRAY_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_SLAB.get().defaultBlockState(), CYAN_SAND_STONE_SLAB.get().defaultBlockState(), PURPLE_SAND_STONE_SLAB.get().defaultBlockState(), BLUE_SAND_STONE_SLAB.get().defaultBlockState(), GREEN_SAND_STONE_SLAB.get().defaultBlockState(), BROWN_SAND_STONE_SLAB.get().defaultBlockState(), BLACK_SAND_STONE_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), OVERRIDE_RED_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLOOD_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), WHITE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), ORANGE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), MAGENTA_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), YELLOW_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIME_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PINK_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GRAY_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), CYAN_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PURPLE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLUE_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GREEN_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BROWN_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLACK_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneSlab || SMOOTH_SANDSTONE_SLAB.defaultBlockState() == state || SMOOTH_RED_SANDSTONE_SLAB.defaultBlockState() == state) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE_SLAB.defaultBlockState(), SMOOTH_RED_SANDSTONE_SLAB.defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), OVERRIDE_RED_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_SLAB_ENERGY.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaSlab) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_SLAB.get().defaultBlockState(), RED_TERRACOTTA_SLAB.get().defaultBlockState(), null, WHITE_TERRACOTTA_SLAB.get().defaultBlockState(), ORANGE_TERRACOTTA_SLAB.get().defaultBlockState(), MAGENTA_TERRACOTTA_SLAB.get().defaultBlockState(), LIGHT_BLUE_TERRACOTTA_SLAB.get().defaultBlockState(), YELLOW_TERRACOTTA_SLAB.get().defaultBlockState(), LIME_TERRACOTTA_SLAB.get().defaultBlockState(), PINK_TERRACOTTA_SLAB.get().defaultBlockState(), GRAY_TERRACOTTA_SLAB.get().defaultBlockState(), LIGHT_GRAY_TERRACOTTA_SLAB.get().defaultBlockState(), CYAN_TERRACOTTA_SLAB.get().defaultBlockState(), PURPLE_TERRACOTTA_SLAB.get().defaultBlockState(), BLUE_TERRACOTTA_SLAB.get().defaultBlockState(), GREEN_TERRACOTTA_SLAB.get().defaultBlockState(), BROWN_TERRACOTTA_SLAB.get().defaultBlockState(), BLACK_TERRACOTTA_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteSlab) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_SLAB.get().defaultBlockState(), null, WHITE_CONCRETE_SLAB.get().defaultBlockState(), ORANGE_CONCRETE_SLAB.get().defaultBlockState(), MAGENTA_CONCRETE_SLAB.get().defaultBlockState(), LIGHT_BLUE_CONCRETE_SLAB.get().defaultBlockState(), YELLOW_CONCRETE_SLAB.get().defaultBlockState(), LIME_CONCRETE_SLAB.get().defaultBlockState(), PINK_CONCRETE_SLAB.get().defaultBlockState(), GRAY_CONCRETE_SLAB.get().defaultBlockState(), LIGHT_GRAY_CONCRETE_SLAB.get().defaultBlockState(), CYAN_CONCRETE_SLAB.get().defaultBlockState(), PURPLE_CONCRETE_SLAB.get().defaultBlockState(), BLUE_CONCRETE_SLAB.get().defaultBlockState(), GREEN_CONCRETE_SLAB.get().defaultBlockState(), BROWN_CONCRETE_SLAB.get().defaultBlockState(), BLACK_CONCRETE_SLAB.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult gen_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 5;
        if (getTerracotta_list().contains(state)) {
            return ColorLogic(world, blockPos, state, TERRACOTTA.defaultBlockState(), RED_TERRACOTTA.defaultBlockState(), null, WHITE_TERRACOTTA.defaultBlockState(), ORANGE_TERRACOTTA.defaultBlockState(), MAGENTA_TERRACOTTA.defaultBlockState(), LIGHT_BLUE_TERRACOTTA.defaultBlockState(), YELLOW_TERRACOTTA.defaultBlockState(), LIME_TERRACOTTA.defaultBlockState(), PINK_TERRACOTTA.defaultBlockState(), GRAY_TERRACOTTA.defaultBlockState(), LIGHT_GRAY_TERRACOTTA.defaultBlockState(), CYAN_TERRACOTTA.defaultBlockState(), PURPLE_TERRACOTTA.defaultBlockState(), BLUE_TERRACOTTA.defaultBlockState(), GREEN_TERRACOTTA.defaultBlockState(), BROWN_TERRACOTTA.defaultBlockState(), BLACK_TERRACOTTA.defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (getConcrete_list().contains(state)) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE.defaultBlockState(), null, WHITE_CONCRETE.defaultBlockState(), ORANGE_CONCRETE.defaultBlockState(), MAGENTA_CONCRETE.defaultBlockState(), LIGHT_BLUE_CONCRETE.defaultBlockState(), YELLOW_CONCRETE.defaultBlockState(), LIME_CONCRETE.defaultBlockState(), PINK_CONCRETE.defaultBlockState(), GRAY_CONCRETE.defaultBlockState(), LIGHT_GRAY_CONCRETE.defaultBlockState(), CYAN_CONCRETE.defaultBlockState(), PURPLE_CONCRETE.defaultBlockState(), BLUE_CONCRETE.defaultBlockState(), GREEN_CONCRETE.defaultBlockState(), BROWN_CONCRETE.defaultBlockState(), BLACK_CONCRETE.defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof chiseledSandStone || state == CHISELED_SANDSTONE.defaultBlockState() || state == CHISELED_RED_SANDSTONE.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, CHISELED_SANDSTONE.defaultBlockState(), CHISELED_RED_SANDSTONE.defaultBlockState(), BLOOD_CHISELED_SAND_STONE.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE.get().defaultBlockState(), LIME_CHISELED_SAND_STONE.get().defaultBlockState(), PINK_CHISELED_SAND_STONE.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof normSandStone || state == SANDSTONE.defaultBlockState() || state == RED_SANDSTONE.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE.defaultBlockState(), RED_SANDSTONE.defaultBlockState(), BLOOD_SAND_STONE.get().defaultBlockState(), WHITE_SAND_STONE.get().defaultBlockState(), ORANGE_SAND_STONE.get().defaultBlockState(), MAGENTA_SAND_STONE.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE.get().defaultBlockState(), YELLOW_SAND_STONE.get().defaultBlockState(), LIME_SAND_STONE.get().defaultBlockState(), PINK_SAND_STONE.get().defaultBlockState(), GRAY_SAND_STONE.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE.get().defaultBlockState(), CYAN_SAND_STONE.get().defaultBlockState(), PURPLE_SAND_STONE.get().defaultBlockState(), BLUE_SAND_STONE.get().defaultBlockState(), GREEN_SAND_STONE.get().defaultBlockState(), BROWN_SAND_STONE.get().defaultBlockState(), BLACK_SAND_STONE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStone || state == SMOOTH_SANDSTONE.defaultBlockState() || state == SMOOTH_RED_SANDSTONE.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE.defaultBlockState(), SMOOTH_RED_SANDSTONE.defaultBlockState(), BLOOD_SMOOTH_SAND_STONE.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult grav_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 5;
        if (block instanceof sandBlock || getSand_list().contains(state)) {
            return ColorLogic(world, blockPos, state, SAND.defaultBlockState(), RED_SAND.defaultBlockState(), BLOOD_SAND.get().defaultBlockState(), WHITE_SAND.get().defaultBlockState(), ORANGE_SAND.get().defaultBlockState(), MAGENTA_SAND.get().defaultBlockState(), LIGHT_BLUE_SAND.get().defaultBlockState(), YELLOW_SAND.get().defaultBlockState(), LIME_SAND.get().defaultBlockState(), PINK_SAND.get().defaultBlockState(), GRAY_SAND.get().defaultBlockState(), LIGHT_GRAY_SAND.get().defaultBlockState(), CYAN_SAND.get().defaultBlockState(), PURPLE_SAND.get().defaultBlockState(), BLUE_SAND.get().defaultBlockState(), GREEN_SAND.get().defaultBlockState(), BROWN_SAND.get().defaultBlockState(), BLACK_SAND.get().defaultBlockState(),blockIndex, inHand, playerEntity);
        }
        if (block instanceof solidSandBlock) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SOLID_SAND.get().defaultBlockState(), OVERRIDE_RED_SOLID_SAND.get().defaultBlockState(), BLOOD_SOLID_SAND.get().defaultBlockState(), WHITE_SOLID_SAND.get().defaultBlockState(), ORANGE_SOLID_SAND.get().defaultBlockState(), MAGENTA_SOLID_SAND.get().defaultBlockState(), LIGHT_BLUE_SOLID_SAND.get().defaultBlockState(), YELLOW_SOLID_SAND.get().defaultBlockState(), LIME_SOLID_SAND.get().defaultBlockState(), PINK_SOLID_SAND.get().defaultBlockState(), GRAY_SOLID_SAND.get().defaultBlockState(), LIGHT_GRAY_SOLID_SAND.get().defaultBlockState(), CYAN_SOLID_SAND.get().defaultBlockState(), PURPLE_SOLID_SAND.get().defaultBlockState(), BLUE_SOLID_SAND.get().defaultBlockState(), GREEN_SOLID_SAND.get().defaultBlockState(), BROWN_SOLID_SAND.get().defaultBlockState(), BLACK_SOLID_SAND.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (getConcretePowder_list().contains(state)) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_POWDER.defaultBlockState(), null, WHITE_CONCRETE_POWDER.defaultBlockState(), ORANGE_CONCRETE_POWDER.defaultBlockState(), MAGENTA_CONCRETE_POWDER.defaultBlockState(), LIGHT_BLUE_CONCRETE_POWDER.defaultBlockState(), YELLOW_CONCRETE_POWDER.defaultBlockState(), LIME_CONCRETE_POWDER.defaultBlockState(), PINK_CONCRETE_POWDER.defaultBlockState(), GRAY_CONCRETE_POWDER.defaultBlockState(), LIGHT_GRAY_CONCRETE_POWDER.defaultBlockState(), CYAN_CONCRETE_POWDER.defaultBlockState(), PURPLE_CONCRETE_POWDER.defaultBlockState(), BLUE_CONCRETE_POWDER.defaultBlockState(), GREEN_CONCRETE_POWDER.defaultBlockState(), BROWN_CONCRETE_POWDER.defaultBlockState(), BLACK_CONCRETE_POWDER.defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult stair_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 2;
        if (block instanceof chiseledSandStoneStair) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), RED_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneStair) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_STAIR.get().defaultBlockState(), RED_CUT_SAND_STONE_STAIR.get().defaultBlockState(), BLOOD_CUT_SAND_STONE_STAIR.get().defaultBlockState(), WHITE_CUT_SAND_STONE_STAIR.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_STAIR.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_STAIR.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_STAIR.get().defaultBlockState(), LIME_CUT_SAND_STONE_STAIR.get().defaultBlockState(), PINK_CUT_SAND_STONE_STAIR.get().defaultBlockState(), GRAY_CUT_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_STAIR.get().defaultBlockState(), CYAN_CUT_SAND_STONE_STAIR.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_STAIR.get().defaultBlockState(), BLUE_CUT_SAND_STONE_STAIR.get().defaultBlockState(), GREEN_CUT_SAND_STONE_STAIR.get().defaultBlockState(), BROWN_CUT_SAND_STONE_STAIR.get().defaultBlockState(), BLACK_CUT_SAND_STONE_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStair) {
            return ColorLogic(world, blockPos, state, SAND_STAIR.get().defaultBlockState(), RED_SAND_STAIR.get().defaultBlockState(), BLOOD_SAND_STAIR.get().defaultBlockState(), WHITE_SAND_STAIR.get().defaultBlockState(), ORANGE_SAND_STAIR.get().defaultBlockState(), MAGENTA_SAND_STAIR.get().defaultBlockState(), LIGHT_BLUE_SAND_STAIR.get().defaultBlockState(), YELLOW_SAND_STAIR.get().defaultBlockState(), LIME_SAND_STAIR.get().defaultBlockState(), PINK_SAND_STAIR.get().defaultBlockState(), GRAY_SAND_STAIR.get().defaultBlockState(), LIGHT_GRAY_SAND_STAIR.get().defaultBlockState(), CYAN_SAND_STAIR.get().defaultBlockState(), PURPLE_SAND_STAIR.get().defaultBlockState(), BLUE_SAND_STAIR.get().defaultBlockState(), GREEN_SAND_STAIR.get().defaultBlockState(), BROWN_SAND_STAIR.get().defaultBlockState(), BLACK_SAND_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneStair || state == SANDSTONE_STAIRS.defaultBlockState() || state == RED_SANDSTONE_STAIRS.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE_STAIRS.defaultBlockState(), RED_SANDSTONE_STAIRS.defaultBlockState(), BLOOD_SAND_STONE_STAIR.get().defaultBlockState(), WHITE_SAND_STONE_STAIR.get().defaultBlockState(), ORANGE_SAND_STONE_STAIR.get().defaultBlockState(), MAGENTA_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_STAIR.get().defaultBlockState(), YELLOW_SAND_STONE_STAIR.get().defaultBlockState(), LIME_SAND_STONE_STAIR.get().defaultBlockState(), PINK_SAND_STONE_STAIR.get().defaultBlockState(), GRAY_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_STAIR.get().defaultBlockState(), CYAN_SAND_STONE_STAIR.get().defaultBlockState(), PURPLE_SAND_STONE_STAIR.get().defaultBlockState(), BLUE_SAND_STONE_STAIR.get().defaultBlockState(), GREEN_SAND_STONE_STAIR.get().defaultBlockState(), BROWN_SAND_STONE_STAIR.get().defaultBlockState(), BLACK_SAND_STONE_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneStair || state == SMOOTH_SANDSTONE_STAIRS.defaultBlockState() || state == SMOOTH_RED_SANDSTONE_STAIRS.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE_STAIRS.defaultBlockState(), SMOOTH_RED_SANDSTONE_STAIRS.defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaStair) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_STAIR.get().defaultBlockState(), RED_TERRACOTTA_STAIR.get().defaultBlockState(), null, WHITE_TERRACOTTA_STAIR.get().defaultBlockState(), ORANGE_TERRACOTTA_STAIR.get().defaultBlockState(), MAGENTA_TERRACOTTA_STAIR.get().defaultBlockState(), LIGHT_BLUE_TERRACOTTA_STAIR.get().defaultBlockState(), YELLOW_TERRACOTTA_STAIR.get().defaultBlockState(), LIME_TERRACOTTA_STAIR.get().defaultBlockState(), PINK_TERRACOTTA_STAIR.get().defaultBlockState(), GRAY_TERRACOTTA_STAIR.get().defaultBlockState(), LIGHT_GRAY_TERRACOTTA_STAIR.get().defaultBlockState(), CYAN_TERRACOTTA_STAIR.get().defaultBlockState(), PURPLE_TERRACOTTA_STAIR.get().defaultBlockState(), BLUE_TERRACOTTA_STAIR.get().defaultBlockState(), GREEN_TERRACOTTA_STAIR.get().defaultBlockState(), BROWN_TERRACOTTA_STAIR.get().defaultBlockState(), BLACK_TERRACOTTA_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteStair) {
            return  ColorLogic(world, blockPos, state, null, RED_CONCRETE_STAIR.get().defaultBlockState(), null, WHITE_CONCRETE_STAIR.get().defaultBlockState(), ORANGE_CONCRETE_STAIR.get().defaultBlockState(), MAGENTA_CONCRETE_STAIR.get().defaultBlockState(), LIGHT_BLUE_CONCRETE_STAIR.get().defaultBlockState(), YELLOW_CONCRETE_STAIR.get().defaultBlockState(), LIME_CONCRETE_STAIR.get().defaultBlockState(), PINK_CONCRETE_STAIR.get().defaultBlockState(), GRAY_CONCRETE_STAIR.get().defaultBlockState(), LIGHT_GRAY_CONCRETE_STAIR.get().defaultBlockState(), CYAN_CONCRETE_STAIR.get().defaultBlockState(), PURPLE_CONCRETE_STAIR.get().defaultBlockState(), BLUE_CONCRETE_STAIR.get().defaultBlockState(), GREEN_CONCRETE_STAIR.get().defaultBlockState(), BROWN_CONCRETE_STAIR.get().defaultBlockState(), BLACK_CONCRETE_STAIR.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult wall_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 1;
        if (block instanceof chiseledSandStoneWall) {
            return ColorLogic(world, blockPos, state, OVERRIDE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), OVERRIDE_RED_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneWall) {
            return ColorLogic(world, blockPos, state, OVERRIDE_CUT_SAND_STONE_WALL.get().defaultBlockState(), OVERRIDE_RED_CUT_SAND_STONE_WALL.get().defaultBlockState(), BLOOD_CUT_SAND_STONE_WALL.get().defaultBlockState(), WHITE_CUT_SAND_STONE_WALL.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_WALL.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_WALL.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_WALL.get().defaultBlockState(), LIME_CUT_SAND_STONE_WALL.get().defaultBlockState(), PINK_CUT_SAND_STONE_WALL.get().defaultBlockState(), GRAY_CUT_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_WALL.get().defaultBlockState(), CYAN_CUT_SAND_STONE_WALL.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_WALL.get().defaultBlockState(), BLUE_CUT_SAND_STONE_WALL.get().defaultBlockState(), GREEN_CUT_SAND_STONE_WALL.get().defaultBlockState(), BROWN_CUT_SAND_STONE_WALL.get().defaultBlockState(), BLACK_CUT_SAND_STONE_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneWall || state == SANDSTONE_WALL.defaultBlockState() || state == RED_SANDSTONE_WALL.defaultBlockState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE_WALL.defaultBlockState(), RED_SANDSTONE_WALL.defaultBlockState(), BLOOD_SAND_STONE_WALL.get().defaultBlockState(), WHITE_SAND_STONE_WALL.get().defaultBlockState(), ORANGE_SAND_STONE_WALL.get().defaultBlockState(), MAGENTA_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_WALL.get().defaultBlockState(), YELLOW_SAND_STONE_WALL.get().defaultBlockState(), LIME_SAND_STONE_WALL.get().defaultBlockState(), PINK_SAND_STONE_WALL.get().defaultBlockState(), GRAY_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_WALL.get().defaultBlockState(), CYAN_SAND_STONE_WALL.get().defaultBlockState(), PURPLE_SAND_STONE_WALL.get().defaultBlockState(), BLUE_SAND_STONE_WALL.get().defaultBlockState(), GREEN_SAND_STONE_WALL.get().defaultBlockState(), BROWN_SAND_STONE_WALL.get().defaultBlockState(), BLACK_SAND_STONE_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandWall) {
            return ColorLogic(world, blockPos, state, OVERRIDE_SAND_WALL.get().defaultBlockState(), OVERRIDE_RED_SAND_WALL.get().defaultBlockState(), BLOOD_SAND_WALL.get().defaultBlockState(), WHITE_SAND_WALL.get().defaultBlockState(), ORANGE_SAND_WALL.get().defaultBlockState(), MAGENTA_SAND_WALL.get().defaultBlockState(), LIGHT_BLUE_SAND_WALL.get().defaultBlockState(), YELLOW_SAND_WALL.get().defaultBlockState(), LIME_SAND_WALL.get().defaultBlockState(), PINK_SAND_WALL.get().defaultBlockState(), GRAY_SAND_WALL.get().defaultBlockState(), LIGHT_GRAY_SAND_WALL.get().defaultBlockState(), CYAN_SAND_WALL.get().defaultBlockState(), PURPLE_SAND_WALL.get().defaultBlockState(), BLUE_SAND_WALL.get().defaultBlockState(), GREEN_SAND_WALL.get().defaultBlockState(), BROWN_SAND_WALL.get().defaultBlockState(), BLACK_SAND_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneWall) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), RED_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaWall) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_WALL.get().defaultBlockState(), RED_TERRACOTTA_WALL.get().defaultBlockState(), null, WHITE_TERRACOTTA_WALL.get().defaultBlockState(), ORANGE_TERRACOTTA_WALL.get().defaultBlockState(), MAGENTA_TERRACOTTA_WALL.get().defaultBlockState(), LIGHT_BLUE_TERRACOTTA_WALL.get().defaultBlockState(), YELLOW_TERRACOTTA_WALL.get().defaultBlockState(), LIME_TERRACOTTA_WALL.get().defaultBlockState(), PINK_TERRACOTTA_WALL.get().defaultBlockState(), GRAY_TERRACOTTA_WALL.get().defaultBlockState(), LIGHT_GRAY_TERRACOTTA_WALL.get().defaultBlockState(), CYAN_TERRACOTTA_WALL.get().defaultBlockState(), PURPLE_TERRACOTTA_WALL.get().defaultBlockState(), BLUE_TERRACOTTA_WALL.get().defaultBlockState(), GREEN_TERRACOTTA_WALL.get().defaultBlockState(), BROWN_TERRACOTTA_WALL.get().defaultBlockState(), BLACK_TERRACOTTA_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteWall) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_WALL.get().defaultBlockState(), null, WHITE_CONCRETE_WALL.get().defaultBlockState(), ORANGE_CONCRETE_WALL.get().defaultBlockState(), MAGENTA_CONCRETE_WALL.get().defaultBlockState(), LIGHT_BLUE_CONCRETE_WALL.get().defaultBlockState(), YELLOW_CONCRETE_WALL.get().defaultBlockState(), LIME_CONCRETE_WALL.get().defaultBlockState(), PINK_CONCRETE_WALL.get().defaultBlockState(), GRAY_CONCRETE_WALL.get().defaultBlockState(), LIGHT_GRAY_CONCRETE_WALL.get().defaultBlockState(), CYAN_CONCRETE_WALL.get().defaultBlockState(), PURPLE_CONCRETE_WALL.get().defaultBlockState(), BLUE_CONCRETE_WALL.get().defaultBlockState(), GREEN_CONCRETE_WALL.get().defaultBlockState(), BROWN_CONCRETE_WALL.get().defaultBlockState(), BLACK_CONCRETE_WALL.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult fence_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 6;
        if (block instanceof chiseledSandStoneFence) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_FENCE.get().defaultBlockState(),RED_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteFence) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_FENCE.get().defaultBlockState(), null, WHITE_CONCRETE_FENCE.get().defaultBlockState(), ORANGE_CONCRETE_FENCE.get().defaultBlockState(), MAGENTA_CONCRETE_FENCE.get().defaultBlockState(), LIGHT_BLUE_CONCRETE_FENCE.get().defaultBlockState(), YELLOW_CONCRETE_FENCE.get().defaultBlockState(), LIME_CONCRETE_FENCE.get().defaultBlockState(), PINK_CONCRETE_FENCE.get().defaultBlockState(), GRAY_CONCRETE_FENCE.get().defaultBlockState(), LIGHT_GRAY_CONCRETE_FENCE.get().defaultBlockState(), CYAN_CONCRETE_FENCE.get().defaultBlockState(), PURPLE_CONCRETE_FENCE.get().defaultBlockState(), BLUE_CONCRETE_FENCE.get().defaultBlockState(), GREEN_CONCRETE_FENCE.get().defaultBlockState(), BROWN_CONCRETE_FENCE.get().defaultBlockState(), BLACK_CONCRETE_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneFence) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_FENCE.get().defaultBlockState(), RED_CUT_SAND_STONE_FENCE.get().defaultBlockState(), BLOOD_CUT_SAND_STONE_FENCE.get().defaultBlockState(), WHITE_CUT_SAND_STONE_FENCE.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_FENCE.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_FENCE.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_FENCE.get().defaultBlockState(), LIME_CUT_SAND_STONE_FENCE.get().defaultBlockState(), PINK_CUT_SAND_STONE_FENCE.get().defaultBlockState(), GRAY_CUT_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_FENCE.get().defaultBlockState(), CYAN_CUT_SAND_STONE_FENCE.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_FENCE.get().defaultBlockState(), BLUE_CUT_SAND_STONE_FENCE.get().defaultBlockState(), GREEN_CUT_SAND_STONE_FENCE.get().defaultBlockState(), BROWN_CUT_SAND_STONE_FENCE.get().defaultBlockState(), BLACK_CUT_SAND_STONE_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandFence) {
            return ColorLogic(world, blockPos, state, SAND_FENCE.get().defaultBlockState(), RED_SAND_FENCE.get().defaultBlockState(), BLOOD_SAND_FENCE.get().defaultBlockState(), WHITE_SAND_FENCE.get().defaultBlockState(), ORANGE_SAND_FENCE.get().defaultBlockState(), MAGENTA_SAND_FENCE.get().defaultBlockState(), LIGHT_BLUE_SAND_FENCE.get().defaultBlockState(), YELLOW_SAND_FENCE.get().defaultBlockState(), LIME_SAND_FENCE.get().defaultBlockState(), PINK_SAND_FENCE.get().defaultBlockState(), GRAY_SAND_FENCE.get().defaultBlockState(), LIGHT_GRAY_SAND_FENCE.get().defaultBlockState(), CYAN_SAND_FENCE.get().defaultBlockState(), PURPLE_SAND_FENCE.get().defaultBlockState(), BLUE_SAND_FENCE.get().defaultBlockState(), GREEN_SAND_FENCE.get().defaultBlockState(), BROWN_SAND_FENCE.get().defaultBlockState(), BLACK_SAND_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneFence) {
            return ColorLogic(world, blockPos, state, SAND_STONE_FENCE.get().defaultBlockState(), RED_SAND_STONE_FENCE.get().defaultBlockState(), BLOOD_SAND_STONE_FENCE.get().defaultBlockState(), WHITE_SAND_STONE_FENCE.get().defaultBlockState(), ORANGE_SAND_STONE_FENCE.get().defaultBlockState(), MAGENTA_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_FENCE.get().defaultBlockState(), YELLOW_SAND_STONE_FENCE.get().defaultBlockState(), LIME_SAND_STONE_FENCE.get().defaultBlockState(), PINK_SAND_STONE_FENCE.get().defaultBlockState(), GRAY_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_FENCE.get().defaultBlockState(), CYAN_SAND_STONE_FENCE.get().defaultBlockState(), PURPLE_SAND_STONE_FENCE.get().defaultBlockState(), BLUE_SAND_STONE_FENCE.get().defaultBlockState(), GREEN_SAND_STONE_FENCE.get().defaultBlockState(), BROWN_SAND_STONE_FENCE.get().defaultBlockState(), BLACK_SAND_STONE_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneFence) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), RED_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaFence) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_FENCE.get().defaultBlockState(), RED_TERRACOTTA_FENCE.get().defaultBlockState(), null, WHITE_TERRACOTTA_FENCE.get().defaultBlockState(), ORANGE_TERRACOTTA_FENCE.get().defaultBlockState(), MAGENTA_TERRACOTTA_FENCE.get().defaultBlockState(), LIGHT_BLUE_TERRACOTTA_FENCE.get().defaultBlockState(), YELLOW_TERRACOTTA_FENCE.get().defaultBlockState(), LIME_TERRACOTTA_FENCE.get().defaultBlockState(), PINK_TERRACOTTA_FENCE.get().defaultBlockState(), GRAY_TERRACOTTA_FENCE.get().defaultBlockState(), LIGHT_GRAY_TERRACOTTA_FENCE.get().defaultBlockState(), CYAN_TERRACOTTA_FENCE.get().defaultBlockState(), PURPLE_TERRACOTTA_FENCE.get().defaultBlockState(), BLUE_TERRACOTTA_FENCE.get().defaultBlockState(), GREEN_TERRACOTTA_FENCE.get().defaultBlockState(), BROWN_TERRACOTTA_FENCE.get().defaultBlockState(), BLACK_TERRACOTTA_FENCE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
    public static InteractionResult fenceGate_select(Level world, BlockPos blockPos, BlockState state, Block block, Player playerEntity, Item inHand) {
        int blockIndex = 7;
        if (block instanceof chiseledSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), RED_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLOOD_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), WHITE_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), ORANGE_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), MAGENTA_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), YELLOW_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIME_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PINK_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GRAY_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), CYAN_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PURPLE_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLUE_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GREEN_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BROWN_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLACK_CHISELED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteFenceGate) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_FENCE_GATE.get().defaultBlockState(), null, WHITE_CONCRETE_FENCE_GATE.get().defaultBlockState(), ORANGE_CONCRETE_FENCE_GATE.get().defaultBlockState(), MAGENTA_CONCRETE_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_CONCRETE_FENCE_GATE.get().defaultBlockState(), YELLOW_CONCRETE_FENCE_GATE.get().defaultBlockState(), LIME_CONCRETE_FENCE_GATE.get().defaultBlockState(), PINK_CONCRETE_FENCE_GATE.get().defaultBlockState(), GRAY_CONCRETE_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_CONCRETE_FENCE_GATE.get().defaultBlockState(), CYAN_CONCRETE_FENCE_GATE.get().defaultBlockState(), PURPLE_CONCRETE_FENCE_GATE.get().defaultBlockState(), BLUE_CONCRETE_FENCE_GATE.get().defaultBlockState(), GREEN_CONCRETE_FENCE_GATE.get().defaultBlockState(), BROWN_CONCRETE_FENCE_GATE.get().defaultBlockState(), BLACK_CONCRETE_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), RED_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLOOD_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), WHITE_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), ORANGE_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), MAGENTA_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), YELLOW_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIME_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PINK_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GRAY_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), CYAN_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PURPLE_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLUE_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GREEN_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BROWN_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLACK_CUT_SAND_STONE_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandFenceGate) {
            return ColorLogic(world, blockPos, state, SAND_FENCE_GATE.get().defaultBlockState(), RED_SAND_FENCE_GATE.get().defaultBlockState(), BLOOD_SAND_FENCE_GATE.get().defaultBlockState(), WHITE_SAND_FENCE_GATE.get().defaultBlockState(), ORANGE_SAND_FENCE_GATE.get().defaultBlockState(), MAGENTA_SAND_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_SAND_FENCE_GATE.get().defaultBlockState(), YELLOW_SAND_FENCE_GATE.get().defaultBlockState(), LIME_SAND_FENCE_GATE.get().defaultBlockState(), PINK_SAND_FENCE_GATE.get().defaultBlockState(), GRAY_SAND_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_SAND_FENCE_GATE.get().defaultBlockState(), CYAN_SAND_FENCE_GATE.get().defaultBlockState(), PURPLE_SAND_FENCE_GATE.get().defaultBlockState(), BLUE_SAND_FENCE_GATE.get().defaultBlockState(), GREEN_SAND_FENCE_GATE.get().defaultBlockState(), BROWN_SAND_FENCE_GATE.get().defaultBlockState(), BLACK_SAND_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, SAND_STONE_FENCE_GATE.get().defaultBlockState(), RED_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLOOD_SAND_STONE_FENCE_GATE.get().defaultBlockState(), WHITE_SAND_STONE_FENCE_GATE.get().defaultBlockState(), ORANGE_SAND_STONE_FENCE_GATE.get().defaultBlockState(), MAGENTA_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_SAND_STONE_FENCE_GATE.get().defaultBlockState(), YELLOW_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIME_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PINK_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GRAY_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_SAND_STONE_FENCE_GATE.get().defaultBlockState(), CYAN_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PURPLE_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLUE_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GREEN_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BROWN_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLACK_SAND_STONE_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), RED_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLOOD_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), WHITE_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), ORANGE_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), MAGENTA_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), YELLOW_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIME_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PINK_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GRAY_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), CYAN_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), PURPLE_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLUE_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), GREEN_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BROWN_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), BLACK_SMOOTH_SAND_STONE_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaFenceGate) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_FENCE_GATE.get().defaultBlockState(), RED_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), null, WHITE_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), ORANGE_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), MAGENTA_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), LIGHT_BLUE_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), YELLOW_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), LIME_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), PINK_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), GRAY_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), LIGHT_GRAY_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), CYAN_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), PURPLE_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), BLUE_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), GREEN_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), BROWN_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), BLACK_TERRACOTTA_FENCE_GATE.get().defaultBlockState(), blockIndex, inHand, playerEntity);
        }
        return InteractionResult.FAIL;
    }
}