
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="${mod_id}"
version="${project.delbase_ver}"
displayName="${mod_name}"
# logoFile="dephoegonlogo.png"
credits="Lack of Sanity, Myself, Trial & Error, Family, and My friend(s) for listening to insanity."
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

